-- ============================================================
-- Tabela: destination_images
-- 562 destinos com URLs de imagens
-- ============================================================

-- 1) Criar a tabela
CREATE TABLE IF NOT EXISTS destination_images (
  id BIGSERIAL PRIMARY KEY,
  city TEXT NOT NULL UNIQUE,
  image_url TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2) Indice para busca por cidade
CREATE INDEX IF NOT EXISTS idx_destination_images_city ON destination_images (city);

-- 3) Inserir todos os destinos (upsert para idempotencia)
INSERT INTO destination_images (city, image_url) VALUES
  ('Bangkok', 'https://nomads.com/assets/img/places/bangkok-thailand.jpg'),
  ('Buenos Aires', 'https://nomads.com/assets/img/places/buenos-aires-argentina.jpg'),
  ('Lisboa', 'https://nomads.com/assets/img/places/lisbon-portugal.jpg'),
  ('Medellín', 'https://nomads.com/assets/img/places/medellin-colombia.jpg'),
  ('Chiang Mai', 'https://nomads.com/assets/img/places/chiang-mai-thailand.jpg'),
  ('Canggu', 'https://nomads.com/assets/img/places/canggu-bali-indonesia.jpg'),
  ('Playa del Carmen', 'https://nomads.com/assets/img/places/playa-del-carmen-mexico.jpg'),
  ('Ho Chi Minh', 'https://nomads.com/assets/img/places/ho-chi-minh-city-vietnam.jpg'),
  ('Tenerife', 'https://nomads.com/assets/img/places/tenerife-canary-islands-spain.jpg'),
  ('Kuala Lumpur', 'https://nomads.com/assets/img/places/kuala-lumpur-malaysia.jpg'),
  ('Tbilisi', 'https://nomads.com/assets/img/places/tbilisi-georgia.jpg'),
  ('Barcelona', 'https://nomads.com/assets/img/places/barcelona-spain.jpg'),
  ('Seul', 'https://nomads.com/assets/img/places/seoul-south-korea.jpg'),
  ('Tóquio', 'https://nomads.com/assets/img/places/tokyo-japan.jpg'),
  ('Berlim', 'https://nomads.com/assets/img/places/berlin-germany.jpg'),
  ('Taipei', 'https://nomads.com/assets/img/places/taipei-taiwan.jpg'),
  ('Porto', 'https://nomads.com/assets/img/places/porto-portugal.jpg'),
  ('Da Nang', 'https://nomads.com/assets/img/places/da-nang-vietnam.jpg'),
  ('Cidade do México', 'https://nomads.com/assets/img/places/mexico-city-mexico.jpg'),
  ('Ubud', 'https://nomads.com/assets/img/places/ubud-bali-indonesia.jpg'),
  ('Split', 'https://nomads.com/assets/img/places/split-croatia.jpg'),
  ('Dubai', 'https://nomads.com/assets/img/places/dubai-united-arab-emirates.jpg'),
  ('Bogotá', 'https://nomads.com/assets/img/places/bogota-colombia.jpg'),
  ('Budapeste', 'https://nomads.com/assets/img/places/budapest-hungary.jpg'),
  ('São Paulo', 'https://nomads.com/assets/img/places/sao-paulo-brazil.jpg'),
  ('Praga', 'https://nomads.com/assets/img/places/prague-czech-republic.jpg'),
  ('Hanói', 'https://nomads.com/assets/img/places/hanoi-vietnam.jpg'),
  ('Rio de Janeiro', 'https://nomads.com/assets/img/places/rio-de-janeiro-brazil.jpg'),
  ('Phuket', 'https://nomads.com/assets/img/places/phuket-thailand.jpg'),
  ('Florianópolis', 'https://nomads.com/assets/img/places/florianopolis-brazil.jpg'),
  ('Curitiba', 'https://nomads.com/assets/img/places/curitiba-brazil.jpg'),
  ('Porto Alegre', 'https://nomads.com/assets/img/places/porto-alegre-brazil.jpg'),
  ('Belo Horizonte', 'https://nomads.com/assets/img/places/belo-horizonte-brazil.jpg'),
  ('Salvador', 'https://nomads.com/assets/img/places/salvador-brazil.jpg'),
  ('Recife', 'https://nomads.com/assets/img/places/recife-brazil.jpg'),
  ('Fortaleza', 'https://nomads.com/assets/img/places/fortaleza-brazil.jpg'),
  ('Natal', 'https://nomads.com/assets/img/places/natal-brazil.jpg'),
  ('Brasília', 'https://nomads.com/assets/img/places/brasilia-brazil.jpg'),
  ('Manaus', 'https://nomads.com/assets/img/places/manaus-brazil.jpg'),
  ('Belém', 'https://nomads.com/assets/img/places/belem-brazil.jpg'),
  ('Goiânia', 'https://nomads.com/assets/img/places/goiania-brazil.jpg'),
  ('João Pessoa', 'https://nomads.com/assets/img/places/joao-pessoa-brazil.jpg'),
  ('Vitória', 'https://nomads.com/assets/img/places/vitoria-brazil.jpg'),
  ('Campinas', 'https://nomads.com/assets/img/places/campinas-brazil.jpg'),
  ('Singapura', 'https://nomads.com/assets/img/places/singapore.jpg'),
  ('Osaka', 'https://nomads.com/assets/img/places/osaka-japan.jpg'),
  ('Busan', 'https://nomads.com/assets/img/places/busan-south-korea.jpg'),
  ('Hong Kong', 'https://nomads.com/assets/img/places/hong-kong.jpg'),
  ('Manila', 'https://nomads.com/assets/img/places/manila-philippines.jpg'),
  ('Cebu', 'https://nomads.com/assets/img/places/cebu-philippines.jpg'),
  ('Phnom Penh', 'https://nomads.com/assets/img/places/phnom-penh-cambodia.jpg'),
  ('Jacarta', 'https://nomads.com/assets/img/places/jakarta-indonesia.jpg'),
  ('Mumbai', 'https://nomads.com/assets/img/places/mumbai-india.jpg'),
  ('Nova Delhi', 'https://nomads.com/assets/img/places/delhi-india.jpg'),
  ('Bangalore', 'https://nomads.com/assets/img/places/bangalore-india.jpg'),
  ('Goa', 'https://nomads.com/assets/img/places/goa-india.jpg'),
  ('Colombo', 'https://nomads.com/assets/img/places/colombo-sri-lanka.jpg'),
  ('Katmandu', 'https://nomads.com/assets/img/places/kathmandu-nepal.jpg'),
  ('Yerevan', 'https://nomads.com/assets/img/places/yerevan-armenia.jpg'),
  ('Siem Reap', 'https://nomads.com/assets/img/places/siem-reap-cambodia.jpg'),
  ('Vientiane', 'https://nomads.com/assets/img/places/vientiane-laos.jpg'),
  ('Penang', 'https://nomads.com/assets/img/places/penang-malaysia.jpg'),
  ('Madri', 'https://nomads.com/assets/img/places/madrid-spain.jpg'),
  ('Munique', 'https://nomads.com/assets/img/places/munich-germany.jpg'),
  ('Paris', 'https://nomads.com/assets/img/places/paris-france.jpg'),
  ('Londres', 'https://nomads.com/assets/img/places/london-united-kingdom.jpg'),
  ('Amsterdã', 'https://nomads.com/assets/img/places/amsterdam-netherlands.jpg'),
  ('Viena', 'https://nomads.com/assets/img/places/vienna-austria.jpg'),
  ('Roma', 'https://nomads.com/assets/img/places/rome-italy.jpg'),
  ('Milão', 'https://nomads.com/assets/img/places/milan-italy.jpg'),
  ('Florença', 'https://nomads.com/assets/img/places/florence-italy.jpg'),
  ('Atenas', 'https://nomads.com/assets/img/places/athens-greece.jpg'),
  ('Istambul', 'https://nomads.com/assets/img/places/istanbul-turkey.jpg'),
  ('Varsóvia', 'https://nomads.com/assets/img/places/warsaw-poland.jpg'),
  ('Cracóvia', 'https://nomads.com/assets/img/places/krakow-poland.jpg'),
  ('Bucareste', 'https://nomads.com/assets/img/places/bucharest-romania.jpg'),
  ('Sófia', 'https://nomads.com/assets/img/places/sofia-bulgaria.jpg'),
  ('Belgrado', 'https://nomads.com/assets/img/places/belgrade-serbia.jpg'),
  ('Zagreb', 'https://nomads.com/assets/img/places/zagreb-croatia.jpg'),
  ('Liubliana', 'https://nomads.com/assets/img/places/ljubljana-slovenia.jpg'),
  ('Tallinn', 'https://nomads.com/assets/img/places/tallinn-estonia.jpg'),
  ('Riga', 'https://nomads.com/assets/img/places/riga-latvia.jpg'),
  ('Vilnius', 'https://nomads.com/assets/img/places/vilnius-lithuania.jpg'),
  ('Helsinque', 'https://nomads.com/assets/img/places/helsinki-finland.jpg'),
  ('Estocolmo', 'https://nomads.com/assets/img/places/stockholm-sweden.jpg'),
  ('Copenhague', 'https://nomads.com/assets/img/places/copenhagen-denmark.jpg'),
  ('Dublin', 'https://nomads.com/assets/img/places/dublin-ireland.jpg'),
  ('Edimburgo', 'https://nomads.com/assets/img/places/edinburgh-united-kingdom.jpg'),
  ('Bruxelas', 'https://nomads.com/assets/img/places/brussels-belgium.jpg'),
  ('Sevilha', 'https://nomads.com/assets/img/places/seville-spain.jpg'),
  ('Valência', 'https://nomads.com/assets/img/places/valencia-spain.jpg'),
  ('Málaga', 'https://nomads.com/assets/img/places/malaga-spain.jpg'),
  ('Nice', 'https://nomads.com/assets/img/places/nice-france.jpg'),
  ('Lyon', 'https://nomads.com/assets/img/places/lyon-france.jpg'),
  ('Zurique', 'https://nomads.com/assets/img/places/zurich-switzerland.jpg'),
  ('Genebra', 'https://nomads.com/assets/img/places/geneva-switzerland.jpg'),
  ('Oslo', 'https://nomads.com/assets/img/places/oslo-norway.jpg'),
  ('Cancún', 'https://nomads.com/assets/img/places/cancun-mexico.jpg'),
  ('Tulum', 'https://nomads.com/assets/img/places/tulum-mexico.jpg'),
  ('Cartagena', 'https://nomads.com/assets/img/places/cartagena-colombia.jpg'),
  ('Lima', 'https://nomads.com/assets/img/places/lima-peru.jpg'),
  ('Cusco', 'https://nomads.com/assets/img/places/cusco-peru.jpg'),
  ('Santiago', 'https://nomads.com/assets/img/places/santiago-chile.jpg'),
  ('Montevidéu', 'https://nomads.com/assets/img/places/montevideo-uruguay.jpg'),
  ('Quito', 'https://nomads.com/assets/img/places/quito-ecuador.jpg'),
  ('San José', 'https://nomads.com/assets/img/places/san-jose-costa-rica.jpg'),
  ('Cidade do Panamá', 'https://nomads.com/assets/img/places/panama-city-panama.jpg'),
  ('Nova York', 'https://nomads.com/assets/img/places/new-york-city-ny-united-states.jpg'),
  ('San Francisco', 'https://nomads.com/assets/img/places/san-francisco-ca-united-states.jpg'),
  ('Los Angeles', 'https://nomads.com/assets/img/places/los-angeles-ca-united-states.jpg'),
  ('Austin', 'https://nomads.com/assets/img/places/austin-tx-united-states.jpg'),
  ('Miami', 'https://nomads.com/assets/img/places/miami-fl-united-states.jpg'),
  ('Chicago', 'https://nomads.com/assets/img/places/chicago-il-united-states.jpg'),
  ('Toronto', 'https://nomads.com/assets/img/places/toronto-canada.jpg'),
  ('Vancouver', 'https://nomads.com/assets/img/places/vancouver-canada.jpg'),
  ('Montreal', 'https://nomads.com/assets/img/places/montreal-canada.jpg'),
  ('Valparaíso', 'https://nomads.com/assets/img/places/valparaiso-chile.jpg'),
  ('Cidade do Cabo', 'https://nomads.com/assets/img/places/cape-town-south-africa.jpg'),
  ('Nairóbi', 'https://nomads.com/assets/img/places/nairobi-kenya.jpg'),
  ('Marrakech', 'https://nomads.com/assets/img/places/marrakech-morocco.jpg'),
  ('Cairo', 'https://nomads.com/assets/img/places/cairo-egypt.jpg'),
  ('Acra', 'https://nomads.com/assets/img/places/accra-ghana.jpg'),
  ('Lagos', 'https://nomads.com/assets/img/places/lagos-nigeria.jpg'),
  ('Dacar', 'https://nomads.com/assets/img/places/dakar-senegal.jpg'),
  ('Adis Abeba', 'https://nomads.com/assets/img/places/addis-ababa-ethiopia.jpg'),
  ('Kigali', 'https://nomads.com/assets/img/places/kigali-rwanda.jpg'),
  ('Zanzibar', 'https://images.unsplash.com/photo-1586861203927-800a5acdcc4d?w=600&q=80'),
  ('Tunis', 'https://nomads.com/assets/img/places/tunis-tunisia.jpg'),
  ('Casablanca', 'https://nomads.com/assets/img/places/casablanca-morocco.jpg'),
  ('Dar es Salaam', 'https://nomads.com/assets/img/places/dar-es-salaam-tanzania.jpg'),
  ('Port Louis', 'https://nomads.com/assets/img/places/port-louis-mauritius.jpg'),
  ('Sydney', 'https://nomads.com/assets/img/places/sydney-australia.jpg'),
  ('Melbourne', 'https://nomads.com/assets/img/places/melbourne-australia.jpg'),
  ('Brisbane', 'https://nomads.com/assets/img/places/brisbane-australia.jpg'),
  ('Auckland', 'https://nomads.com/assets/img/places/auckland-new-zealand.jpg'),
  ('Wellington', 'https://nomads.com/assets/img/places/wellington-new-zealand.jpg'),
  ('Gold Coast', 'https://nomads.com/assets/img/places/gold-coast-australia.jpg'),
  ('Perth', 'https://nomads.com/assets/img/places/perth-australia.jpg'),
  ('Abu Dhabi', 'https://nomads.com/assets/img/places/abu-dhabi-united-arab-emirates.jpg'),
  ('Tel Aviv', 'https://nomads.com/assets/img/places/tel-aviv-israel.jpg'),
  ('Amã', 'https://nomads.com/assets/img/places/amman-jordan.jpg'),
  ('Doha', 'https://nomads.com/assets/img/places/doha-qatar.jpg'),
  ('Mascate', 'https://nomads.com/assets/img/places/muscat-oman.jpg'),
  ('Beirute', 'https://nomads.com/assets/img/places/beirut-lebanon.jpg'),
  ('Chiang Rai', 'https://nomads.com/assets/img/places/chiang-rai-thailand.jpg'),
  ('Koh Samui', 'https://nomads.com/assets/img/places/ko-samui-thailand.jpg'),
  ('Luang Prabang', 'https://nomads.com/assets/img/places/luang-prabang-laos.jpg'),
  ('Hoi An', 'https://nomads.com/assets/img/places/hoi-an-vietnam.jpg'),
  ('Nha Trang', 'https://nomads.com/assets/img/places/nha-trang-vietnam.jpg'),
  ('Langkawi', 'https://nomads.com/assets/img/places/langkawi-malaysia.jpg'),
  ('Yogyakarta', 'https://nomads.com/assets/img/places/yogyakarta-indonesia.jpg'),
  ('Seminyak', 'https://nomads.com/assets/img/places/seminyak-bali-indonesia.jpg'),
  ('Quioto', 'https://nomads.com/assets/img/places/kyoto-japan.jpg'),
  ('Fukuoka', 'https://nomads.com/assets/img/places/fukuoka-japan.jpg'),
  ('Ilha de Jeju', 'https://nomads.com/assets/img/places/jeju-island-south-korea.jpg'),
  ('Batumi', 'https://nomads.com/assets/img/places/batumi-georgia.jpg'),
  ('Antalya', 'https://nomads.com/assets/img/places/antalya-turkey.jpg'),
  ('Dubrovnik', 'https://nomads.com/assets/img/places/dubrovnik-croatia.jpg'),
  ('Tessalônica', 'https://nomads.com/assets/img/places/thessaloniki-greece.jpg'),
  ('Kotor', 'https://nomads.com/assets/img/places/kotor-montenegro.jpg'),
  ('Tirana', 'https://nomads.com/assets/img/places/tirana-albania.jpg'),
  ('Skopje', 'https://nomads.com/assets/img/places/skopje-north-macedonia.jpg'),
  ('Sarajevo', 'https://nomads.com/assets/img/places/sarajevo-bosnia.jpg'),
  ('Palermo', 'https://nomads.com/assets/img/places/palermo-italy.jpg'),
  ('Nápoles', 'https://nomads.com/assets/img/places/naples-italy.jpg'),
  ('Cascais', 'https://nomads.com/assets/img/places/cascais-portugal.jpg'),
  ('Lagos (Algarve)', 'https://nomads.com/assets/img/places/lagos-portugal.jpg'),
  ('Granada', 'https://nomads.com/assets/img/places/granada-spain.jpg'),
  ('San Sebastián', 'https://nomads.com/assets/img/places/san-sebastian-spain.jpg'),
  ('Bordeaux', 'https://nomads.com/assets/img/places/bordeaux-france.jpg'),
  ('Marselha', 'https://nomads.com/assets/img/places/marseille-france.jpg'),
  ('Hamburgo', 'https://nomads.com/assets/img/places/hamburg-germany.jpg'),
  ('Ericeira', 'https://nomads.com/assets/img/places/ericeira-portugal.jpg'),
  ('Portland', 'https://nomads.com/assets/img/places/portland-or-united-states.jpg'),
  ('Seattle', 'https://nomads.com/assets/img/places/seattle-wa-united-states.jpg'),
  ('Denver', 'https://nomads.com/assets/img/places/denver-co-united-states.jpg'),
  ('Oaxaca', 'https://nomads.com/assets/img/places/oaxaca-mexico.jpg'),
  ('Puerto Vallarta', 'https://nomads.com/assets/img/places/puerto-vallarta-mexico.jpg'),
  ('Guadalajara', 'https://nomads.com/assets/img/places/guadalajara-mexico.jpg'),
  ('San Miguel de Allende', 'https://nomads.com/assets/img/places/san-miguel-de-allende-mexico.jpg'),
  ('Cali', 'https://nomads.com/assets/img/places/cali-colombia.jpg'),
  ('Santa Marta', 'https://nomads.com/assets/img/places/santa-marta-colombia.jpg'),
  ('La Paz', 'https://nomads.com/assets/img/places/la-paz-bolivia.jpg'),
  ('Assunção', 'https://nomads.com/assets/img/places/asuncion-paraguay.jpg'),
  ('Guayaquil', 'https://nomads.com/assets/img/places/guayaquil-ecuador.jpg'),
  ('Cuenca', 'https://nomads.com/assets/img/places/cuenca-ecuador.jpg'),
  ('Havana', 'https://nomads.com/assets/img/places/havana-cuba.jpg'),
  ('Kingston', 'https://nomads.com/assets/img/places/kingston-jamaica.jpg'),
  ('Santo Domingo', 'https://nomads.com/assets/img/places/santo-domingo-dominican-republic.jpg'),
  ('Antigua', 'https://nomads.com/assets/img/places/antigua-guatemala.jpg'),
  ('Punta Cana', 'https://nomads.com/assets/img/places/punta-cana-dominican-republic.jpg'),
  ('Baku', 'https://nomads.com/assets/img/places/baku-azerbaijan.jpg'),
  ('Reykjavik', 'https://nomads.com/assets/img/places/reykjavik-iceland.jpg'),
  ('Pokhara', 'https://nomads.com/assets/img/places/pokhara-nepal.jpg'),
  ('Galle', 'https://nomads.com/assets/img/places/galle-sri-lanka.jpg'),
  ('Almaty', 'https://nomads.com/assets/img/places/almaty-kazakhstan.jpg'),
  ('Tashkent', 'https://nomads.com/assets/img/places/tashkent-uzbekistan.jpg'),
  ('Siargao', 'https://nomads.com/assets/img/places/siargao-philippines.jpg'),
  ('Riade', 'https://nomads.com/assets/img/places/riyadh-saudi-arabia.jpg'),
  ('Jeddah', 'https://nomads.com/assets/img/places/jeddah-saudi-arabia.jpg'),
  ('Windhoek', 'https://nomads.com/assets/img/places/windhoek-namibia.jpg'),
  ('Adelaide', 'https://nomads.com/assets/img/places/adelaide-australia.jpg'),
  ('Queenstown', 'https://nomads.com/assets/img/places/queenstown-new-zealand.jpg'),
  ('Nadi', 'https://images.unsplash.com/photo-1507699622108-4be3abd695ad?w=600&q=80'),
  ('Apia', 'https://nomads.com/assets/img/places/apia-samoa.jpg'),
  ('Suva', 'https://nomads.com/assets/img/places/suva-fiji.jpg'),
  ('Chennai', 'https://nomads.com/assets/img/places/chennai-india.jpg'),
  ('Jaipur', 'https://nomads.com/assets/img/places/jaipur-india.jpg'),
  ('Kochi', 'https://nomads.com/assets/img/places/kochi-india.jpg'),
  ('Jiufen', 'https://images.unsplash.com/photo-1513023840371-dd774fcaee5b?w=600&q=80'),
  ('Kaohsiung', 'https://nomads.com/assets/img/places/kaohsiung-taiwan.jpg'),
  ('Mtskheta', 'https://images.unsplash.com/photo-1565008576549-57569a49371d?w=600&q=80'),
  ('Pocitos (Montevidéu)', 'https://nomads.com/assets/img/places/montevideo-uruguay.jpg'),
  ('Arequipa', 'https://nomads.com/assets/img/places/arequipa-peru.jpg'),
  ('Tamarindo', 'https://nomads.com/assets/img/places/tamarindo-costa-rica.jpg'),
  ('Cairns', 'https://nomads.com/assets/img/places/cairns-australia.jpg'),
  ('Nouméa', 'https://nomads.com/assets/img/places/noumea-new-caledonia.jpg'),
  ('Ghent', 'https://nomads.com/assets/img/places/ghent-belgium.jpg'),
  ('Gdansk', 'https://nomads.com/assets/img/places/gdansk-poland.jpg'),
  ('Cluj-Napoca', 'https://nomads.com/assets/img/places/cluj-romania.jpg'),
  ('Essaouira', 'https://nomads.com/assets/img/places/essaouira-morocco.jpg'),
  ('Santa Maria (Sal)', 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=600&q=80'),
  ('Kampala', 'https://nomads.com/assets/img/places/kampala-uganda.jpg'),
  ('George Town', 'https://nomads.com/assets/img/places/penang-malaysia.jpg'),
  ('Ipoh', 'https://nomads.com/assets/img/places/ipoh-malaysia.jpg'),
  ('Mandalay', 'https://nomads.com/assets/img/places/mandalay-myanmar.jpg'),
  ('Negombo', 'https://images.unsplash.com/photo-1586613835259-5c51d8e8a47f?w=600&q=80'),
  ('Bratislava', 'https://nomads.com/assets/img/places/bratislava-slovakia.jpg'),
  ('Ljubljana', 'https://nomads.com/assets/img/places/ljubljana-slovenia.jpg'),
  ('Ulan Bator', 'https://nomads.com/assets/img/places/ulaanbaatar-mongolia.jpg'),
  ('La Paz (BCS)', 'https://nomads.com/assets/img/places/la-paz-mexico.jpg'),
  ('Mérida', 'https://nomads.com/assets/img/places/merida-mexico.jpg'),
  ('Sucre', 'https://images.unsplash.com/photo-1564500020755-258bfe4d4ff4?w=600&q=80'),
  ('Córdoba', 'https://nomads.com/assets/img/places/cordoba-spain.jpg'),
  ('San Carlos de Bariloche', 'https://nomads.com/assets/img/places/bariloche-argentina.jpg'),
  ('Budva', 'https://nomads.com/assets/img/places/budva-montenegro.jpg'),
  ('Fez', 'https://nomads.com/assets/img/places/fes-morocco.jpg'),
  ('Maputo', 'https://nomads.com/assets/img/places/maputo-mozambique.jpg'),
  ('Lamu', 'https://images.unsplash.com/photo-1523805009345-7448845a9e53?w=600&q=80'),
  ('Pune', 'https://nomads.com/assets/img/places/pune-india.jpg'),
  ('Panaji (Goa)', 'https://nomads.com/assets/img/places/goa-india.jpg'),
  ('Varna', 'https://nomads.com/assets/img/places/varna-bulgaria.jpg'),
  ('Nicósia', 'https://nomads.com/assets/img/places/nicosia-cyprus.jpg'),
  ('Valletta', 'https://nomads.com/assets/img/places/malta.jpg'),
  ('Lausanne', 'https://nomads.com/assets/img/places/lausanne-switzerland.jpg'),
  ('Inverness', 'https://images.unsplash.com/photo-1648674136198-86bab411a319?w=800&q=80'),
  ('Las Palmas', 'https://nomads.com/assets/img/places/las-palmas-gran-canaria-spain.jpg'),
  ('Chefchaouen', 'https://images.unsplash.com/photo-1509822929063-6b6cfc9b42f2?w=600&q=80'),
  ('Hué', 'https://nomads.com/assets/img/places/hue-vietnam.jpg'),
  ('Ella', 'https://images.unsplash.com/photo-1586613835259-5c51d8e8a47f?w=600&q=80'),
  ('Mussoorie', 'https://images.unsplash.com/photo-1570168007204-dfb528c6958f?w=600&q=80'),
  ('Taghazout', 'https://nomads.com/assets/img/places/taghazout-morocco.jpg'),
  ('Bruges', 'https://nomads.com/assets/img/places/bruges-belgium.jpg'),
  ('Tegallalang', 'https://nomads.com/assets/img/places/ubud-bali-indonesia.jpg'),
  ('Salta', 'https://nomads.com/assets/img/places/salta-argentina.jpg'),
  ('Mendoza', 'https://nomads.com/assets/img/places/mendoza-argentina.jpg'),
  ('Cochabamba', 'https://nomads.com/assets/img/places/cochabamba-bolivia.jpg'),
  ('Oranjestad', 'https://nomads.com/assets/img/places/aruba.jpg'),
  ('Bucaramanga', 'https://nomads.com/assets/img/places/bucaramanga-colombia.jpg'),
  ('Paramaribo', 'https://nomads.com/assets/img/places/paramaribo-suriname.jpg'),
  ('Viña del Mar', 'https://nomads.com/assets/img/places/vina-del-mar-chile.jpg'),
  ('Punta del Este', 'https://nomads.com/assets/img/places/punta-del-este-uruguay.jpg'),
  ('Chachapoyas', 'https://nomads.com/assets/img/places/chachapoyas-peru.jpg'),
  ('Jundiaí', 'https://nomads.com/assets/img/places/jundiai-brazil.jpg'),
  ('Montañita', 'https://nomads.com/assets/img/places/montanita-ecuador.jpg'),
  ('Salento', 'https://nomads.com/assets/img/places/salento-colombia.jpg'),
  ('Willemstad', 'https://nomads.com/assets/img/places/curacao.jpg'),
  ('La Plata', 'https://nomads.com/assets/img/places/la-plata-argentina.jpg'),
  ('Pipa', 'https://nomads.com/assets/img/places/pipa-brazil.jpg'),
  ('Itajaí', 'https://nomads.com/assets/img/places/itajai-brazil.jpg'),
  ('Rosario', 'https://nomads.com/assets/img/places/rosario-argentina.jpg'),
  ('Santa Cruz', 'https://nomads.com/assets/img/places/santa-cruz-bolivia.jpg'),
  ('Basse-Terre', 'https://nomads.com/assets/img/places/basse-terre-guadeloupe.jpg'),
  ('Máncora', 'https://nomads.com/assets/img/places/mancora-peru.jpg'),
  ('Kralendijk', 'https://nomads.com/assets/img/places/kralendijk-caribbean-netherlands.jpg'),
  ('São José dos Campos', 'https://nomads.com/assets/img/places/sao-jose-dos-campos-brazil.jpg'),
  ('Trancoso', 'https://nomads.com/assets/img/places/trancoso-brazil.jpg'),
  ('Sorocaba', 'https://nomads.com/assets/img/places/sorocaba-brazil.jpg'),
  ('Mar del Plata', 'https://nomads.com/assets/img/places/mar-del-plata-argentina.jpg'),
  ('Campo Grande', 'https://nomads.com/assets/img/places/campo-grande-brazil.jpg'),
  ('Georgetown', 'https://nomads.com/assets/img/places/georgetown-guyana.jpg'),
  ('Foz do Iguaçu', 'https://nomads.com/assets/img/places/foz-do-iguacu-brazil.jpg'),
  ('Anápolis', 'https://nomads.com/assets/img/places/anapolis-brazil.jpg'),
  ('St. George''s', 'https://nomads.com/assets/img/places/st-georges-grenada.jpg'),
  ('El Alto', 'https://nomads.com/assets/img/places/el-alto-bolivia.jpg'),
  ('São Luís', 'https://nomads.com/assets/img/places/sao-luis-brazil.jpg'),
  ('La Serena', 'https://nomads.com/assets/img/places/la-serena-chile.jpg'),
  ('Iquique', 'https://nomads.com/assets/img/places/iquique-chile.jpg'),
  ('Campos dos Goytacazes', 'https://nomads.com/assets/img/places/campos-dos-goytacazes-brazil.jpg'),
  ('Itapema', 'https://nomads.com/assets/img/places/itapema-brazil.jpg'),
  ('San Pedro de Atacama', 'https://nomads.com/assets/img/places/san-pedro-de-atacama-chile.jpg'),
  ('Maracaibo', 'https://nomads.com/assets/img/places/maracaibo-venezuela.jpg'),
  ('Pasto', 'https://nomads.com/assets/img/places/pasto-colombia.jpg'),
  ('Antofagasta', 'https://nomads.com/assets/img/places/antofagasta-chile.jpg'),
  ('Maracay', 'https://nomads.com/assets/img/places/maracay-venezuela.jpg'),
  ('Intag Valley', 'https://nomads.com/assets/img/places/intag-valley-ecuador.jpg'),
  ('Port of Spain', 'https://nomads.com/assets/img/places/port-of-spain-trinidad-and-tobago.jpg'),
  ('Uberlândia', 'https://nomads.com/assets/img/places/uberlandia-brazil.jpg'),
  ('Caracas', 'https://nomads.com/assets/img/places/caracas-venezuela.jpg'),
  ('Bridgetown', 'https://nomads.com/assets/img/places/bridgetown-barbados.jpg'),
  ('St. John''s', 'https://nomads.com/assets/img/places/st-johns-antigua-and-barbuda.jpg'),
  ('Martinica', 'https://nomads.com/assets/img/places/martinique.jpg'),
  ('Cayenne', 'https://nomads.com/assets/img/places/cayenne-french-guiana.jpg'),
  ('Tabatinga', 'https://images.unsplash.com/photo-1618681738822-076049b6e573?w=600&q=80'),
  ('Querétaro', 'https://nomads.com/assets/img/places/queretaro-mexico.jpg'),
  ('San Salvador', 'https://nomads.com/assets/img/places/san-salvador-el-salvador.jpg'),
  ('Montego Bay', 'https://nomads.com/assets/img/places/montego-bay-jamaica.jpg'),
  ('Cabarete', 'https://nomads.com/assets/img/places/cabarete-dominican-republic.jpg'),
  ('San Juan', 'https://nomads.com/assets/img/places/san-juan-puerto-rico.jpg'),
  ('Puerto Viejo', 'https://nomads.com/assets/img/places/puerto-viejo-costa-rica.jpg'),
  ('Monterrey', 'https://nomads.com/assets/img/places/monterrey-mexico.jpg'),
  ('Torreón', 'https://nomads.com/assets/img/places/torreon-mexico.jpg'),
  ('Puebla', 'https://nomads.com/assets/img/places/puebla-mexico.jpg'),
  ('Ilhas Galápagos', 'https://nomads.com/assets/img/places/galapagos-islands-ecuador.jpg'),
  ('Ushuaia', 'https://nomads.com/assets/img/places/ushuaia-argentina.jpg'),
  ('Jarabacoa', 'https://nomads.com/assets/img/places/jarabacoa-dominican-republic.jpg'),
  ('Nassau', 'https://nomads.com/assets/img/places/nassau-the-bahamas.jpg'),
  ('Caye Caulker', 'https://nomads.com/assets/img/places/caye-caulker-belize.jpg'),
  ('Liberia', 'https://nomads.com/assets/img/places/liberia-costa-rica.jpg'),
  ('Managua', 'https://nomads.com/assets/img/places/managua-nicaragua.jpg'),
  ('Tijuana', 'https://nomads.com/assets/img/places/tijuana-mexico.jpg'),
  ('Toluca', 'https://nomads.com/assets/img/places/toluca-mexico.jpg'),
  ('Cidade da Guatemala', 'https://nomads.com/assets/img/places/guatemala-city-guatemala.jpg'),
  ('Cozumel', 'https://nomads.com/assets/img/places/cozumel-mexico.jpg'),
  ('Bocas del Toro', 'https://nomads.com/assets/img/places/bocas-del-toro-panama.jpg'),
  ('Puerto Escondido', 'https://nomads.com/assets/img/places/puerto-escondido-mexico.jpg'),
  ('Isla Mujeres', 'https://nomads.com/assets/img/places/isla-mujeres-mexico.jpg'),
  ('Islas de la Bahía', 'https://images.unsplash.com/photo-1570137491981-c5b1c0a25e2f?w=600&q=80'),
  ('San Juan del Sur', 'https://nomads.com/assets/img/places/san-juan-del-sur-nicaragua.jpg'),
  ('Panajachel', 'https://nomads.com/assets/img/places/panajachel-guatemala.jpg'),
  ('Aguascalientes', 'https://nomads.com/assets/img/places/aguascalientes-mexico.jpg'),
  ('León', 'https://nomads.com/assets/img/places/leon-nicaragua.jpg'),
  ('San Pedro Sula', 'https://nomads.com/assets/img/places/san-pedro-sula-honduras.jpg'),
  ('San Cristóbal de las Casas', 'https://nomads.com/assets/img/places/san-cristobal-de-las-casas-mexico.jpg'),
  ('Porto Príncipe', 'https://nomads.com/assets/img/places/port-au-prince-haiti.jpg'),
  ('Hermosillo', 'https://nomads.com/assets/img/places/hermosillo-mexico.jpg'),
  ('Tegucigalpa', 'https://nomads.com/assets/img/places/tegucigalpa-honduras.jpg'),
  ('San Luis Potosí', 'https://nomads.com/assets/img/places/san-luis-potosi-mexico.jpg'),
  ('Barranquilla', 'https://nomads.com/assets/img/places/barranquilla-colombia.jpg'),
  ('Philipsburg', 'https://nomads.com/assets/img/places/philipsburg-sint-maarten.jpg'),
  ('Juárez', 'https://nomads.com/assets/img/places/juarez-mexico.jpg'),
  ('King Edward Point', 'https://nomads.com/assets/img/places/king-edward-point-south-georgia-and-the-south-sandwich-islands.jpg'),
  ('Road Town', 'https://nomads.com/assets/img/places/road-town-british-virgin-islands.jpg'),
  ('Mexicali', 'https://nomads.com/assets/img/places/mexicali-mexico.jpg'),
  ('Santa Teresa', 'https://nomads.com/assets/img/places/santa-teresa-costa-rica.jpg'),
  ('Charlotte Amalie', 'https://nomads.com/assets/img/places/charlotte-amalie-united-states-virgin-islands.jpg'),
  ('Stanley', 'https://nomads.com/assets/img/places/stanley-falkland-islands.jpg'),
  ('Sayulita', 'https://nomads.com/assets/img/places/sayulita-mexico.jpg'),
  ('Guanajuato', 'https://nomads.com/assets/img/places/guanajuato-mexico.jpg'),
  ('Hamilton', 'https://nomads.com/assets/img/places/hamilton-bermuda.jpg'),
  ('Belize City', 'https://nomads.com/assets/img/places/belize-city-belize.jpg'),
  ('Copán', 'https://nomads.com/assets/img/places/copan-honduras.jpg'),
  ('Minca', 'https://nomads.com/assets/img/places/minca-colombia.jpg'),
  ('Cabo San Lucas', 'https://nomads.com/assets/img/places/cabo-san-lucas-mexico.jpg'),
  ('El Calafate', 'https://nomads.com/assets/img/places/el-calafate-argentina.jpg'),
  ('San Ignacio', 'https://nomads.com/assets/img/places/san-ignacio-belize.jpg'),
  ('San Pedro', 'https://nomads.com/assets/img/places/san-pedro-belize.jpg'),
  ('Dallas', 'https://nomads.com/assets/img/places/dallas-united-states.jpg'),
  ('Columbus', 'https://nomads.com/assets/img/places/columbus-oh-united-states.jpg'),
  ('Ogden', 'https://nomads.com/assets/img/places/ogden-ut-united-states.jpg'),
  ('Battle Creek', 'https://nomads.com/assets/img/places/battle-creek-mi-united-states.jpg'),
  ('Amarillo', 'https://nomads.com/assets/img/places/amarillo-tx-united-states.jpg'),
  ('Honolulu', 'https://nomads.com/assets/img/places/honolulu-united-states.jpg'),
  ('Greeley', 'https://nomads.com/assets/img/places/greeley-co-united-states.jpg'),
  ('Atlanta', 'https://nomads.com/assets/img/places/atlanta-united-states.jpg'),
  ('Memphis', 'https://nomads.com/assets/img/places/memphis-tn-united-states.jpg'),
  ('Winnipeg', 'https://nomads.com/assets/img/places/winnipeg-canada.jpg'),
  ('Pittsburgh', 'https://nomads.com/assets/img/places/pittsburgh-pa-united-states.jpg'),
  ('Cincinnati', 'https://nomads.com/assets/img/places/cincinnati-oh-united-states.jpg'),
  ('Tampa', 'https://nomads.com/assets/img/places/tampa-united-states.jpg'),
  ('Fresno', 'https://nomads.com/assets/img/places/fresno-ca-united-states.jpg'),
  ('Chattanooga', 'https://nomads.com/assets/img/places/chattanooga-tn-united-states.jpg'),
  ('Oxnard', 'https://nomads.com/assets/img/places/oxnard-ca-united-states.jpg'),
  ('Louisville', 'https://nomads.com/assets/img/places/louisville-ky-united-states.jpg'),
  ('Oklahoma City', 'https://nomads.com/assets/img/places/oklahoma-city-ok-united-states.jpg'),
  ('Grand Rapids', 'https://nomads.com/assets/img/places/grand-rapids-mi-united-states.jpg'),
  ('Des Moines', 'https://nomads.com/assets/img/places/des-moines-ia-united-states.jpg'),
  ('San Antonio', 'https://nomads.com/assets/img/places/san-antonio-united-states.jpg'),
  ('Timișoara', 'https://nomads.com/assets/img/places/timisoara-romania.jpg'),
  ('Açores', 'https://nomads.com/assets/img/places/azores-portugal.jpg'),
  ('Madeira', 'https://nomads.com/assets/img/places/madeira-portugal.jpg'),
  ('Aveiro', 'https://nomads.com/assets/img/places/aveiro-portugal.jpg'),
  ('Ploiești', 'https://nomads.com/assets/img/places/ploiesti-romania.jpg'),
  ('Portimão', 'https://nomads.com/assets/img/places/portimao-portugal.jpg'),
  ('Coimbra', 'https://nomads.com/assets/img/places/coimbra-portugal.jpg'),
  ('Rijeka', 'https://nomads.com/assets/img/places/rijeka-croatia.jpg'),
  ('Faro', 'https://nomads.com/assets/img/places/faro-portugal.jpg'),
  ('Costa da Caparica', 'https://nomads.com/assets/img/places/costa-da-caparica-portugal.jpg'),
  ('Craiova', 'https://nomads.com/assets/img/places/craiova-romania.jpg'),
  ('Adana', 'https://nomads.com/assets/img/places/adana-turkey.jpg'),
  ('Niš', 'https://nomads.com/assets/img/places/nis-serbia.jpg'),
  ('Burgas', 'https://nomads.com/assets/img/places/burgas-bulgaria.jpg'),
  ('Andorra la Vella', 'https://nomads.com/assets/img/places/andorra-la-vella-andorra.jpg'),
  ('Tartu', 'https://nomads.com/assets/img/places/tartu-estonia.jpg'),
  ('Pátras', 'https://nomads.com/assets/img/places/patras-greece.jpg'),
  ('Aachen', 'https://nomads.com/assets/img/places/aachen-germany.jpg'),
  ('Nuremberg', 'https://nomads.com/assets/img/places/nuremberg-germany.jpg'),
  ('Wrocław', 'https://nomads.com/assets/img/places/wroclaw-poland.jpg'),
  ('Brașov', 'https://nomads.com/assets/img/places/brasov-romania.jpg'),
  ('Lublin', 'https://nomads.com/assets/img/places/lublin-poland.jpg'),
  ('Zadar', 'https://nomads.com/assets/img/places/zadar-croatia.jpg'),
  ('Peniche', 'https://nomads.com/assets/img/places/peniche-portugal.jpg'),
  ('Kutaisi', 'https://nomads.com/assets/img/places/kutaisi-georgia.jpg'),
  ('Łódź', 'https://nomads.com/assets/img/places/lodz-poland.jpg'),
  ('Karlsruhe', 'https://nomads.com/assets/img/places/karlsruhe-germany.jpg'),
  ('Alanya', 'https://nomads.com/assets/img/places/alanya-turkey.jpg'),
  ('Mostar', 'https://nomads.com/assets/img/places/mostar-bosnia.jpg'),
  ('Novi Sad', 'https://nomads.com/assets/img/places/novi-sad-serbia.jpg'),
  ('Utrecht', 'https://nomads.com/assets/img/places/utrecht-netherlands.jpg'),
  ('Gran Canaria', 'https://nomads.com/assets/img/places/gran-canaria-canary-islands-spain.jpg'),
  ('Groningen', 'https://nomads.com/assets/img/places/groningen-netherlands.jpg'),
  ('Frankfurt', 'https://nomads.com/assets/img/places/frankfurt-germany.jpg'),
  ('Leiden', 'https://nomads.com/assets/img/places/leiden-netherlands.jpg'),
  ('Košice', 'https://nomads.com/assets/img/places/kosice-slovakia.jpg'),
  ('Nottingham', 'https://nomads.com/assets/img/places/nottingham-united-kingdom.jpg'),
  ('Bristol', 'https://nomads.com/assets/img/places/bristol-united-kingdom.jpg'),
  ('Lago Balaton', 'https://nomads.com/assets/img/places/budapest-hungary.jpg'),
  ('Norwich', 'https://nomads.com/assets/img/places/norwich-united-kingdom.jpg'),
  ('Catania', 'https://nomads.com/assets/img/places/catania-italy.jpg'),
  ('Newcastle', 'https://nomads.com/assets/img/places/newcastle-upon-tyne-united-kingdom.jpg'),
  ('Alicante', 'https://nomads.com/assets/img/places/alicante-spain.jpg'),
  ('Leeds', 'https://nomads.com/assets/img/places/leeds-united-kingdom.jpg'),
  ('Bremen', 'https://nomads.com/assets/img/places/bremen-germany.jpg'),
  ('Arnhem', 'https://nomads.com/assets/img/places/arnhem-netherlands.jpg'),
  ('Plovdiv', 'https://nomads.com/assets/img/places/plovdiv-bulgaria.jpg'),
  ('Liverpool', 'https://nomads.com/assets/img/places/liverpool-united-kingdom.jpg'),
  ('Lago Como', 'https://nomads.com/assets/img/places/lake-como-italy.jpg'),
  ('Grenoble', 'https://nomads.com/assets/img/places/grenoble-france.jpg'),
  ('Bournemouth', 'https://nomads.com/assets/img/places/bournemouth-united-kingdom.jpg'),
  ('Chișinău', 'https://nomads.com/assets/img/places/chisinau-moldova.jpg'),
  ('Gaziantep', 'https://nomads.com/assets/img/places/gaziantep-turkey.jpg'),
  ('Bodrum', 'https://nomads.com/assets/img/places/bodrum-turkey.jpg'),
  ('Rodes', 'https://nomads.com/assets/img/places/rhodes-greece.jpg'),
  ('Erlangen', 'https://nomads.com/assets/img/places/erlangen-germany.jpg'),
  ('Rethymno', 'https://nomads.com/assets/img/places/rethymno-greece.jpg'),
  ('Cork', 'https://nomads.com/assets/img/places/cork-ireland.jpg'),
  ('Rennes', 'https://nomads.com/assets/img/places/rennes-france.jpg'),
  ('Bursa', 'https://nomads.com/assets/img/places/bursa-turkey.jpg'),
  ('Salzburg', 'https://nomads.com/assets/img/places/salzburg-austria.jpg'),
  ('Basileia', 'https://nomads.com/assets/img/places/basel-switzerland.jpg'),
  ('Poznań', 'https://nomads.com/assets/img/places/poznan-poland.jpg'),
  ('Cannes', 'https://nomads.com/assets/img/places/cannes-france.jpg'),
  ('Pristina', 'https://nomads.com/assets/img/places/pristina-kosovo.jpg'),
  ('Leipzig', 'https://nomads.com/assets/img/places/leipzig-germany.jpg'),
  ('Bath', 'https://nomads.com/assets/img/places/bath-united-kingdom.jpg'),
  ('Heidelberg', 'https://nomads.com/assets/img/places/heidelberg-germany.jpg'),
  ('Manchester', 'https://nomads.com/assets/img/places/manchester-united-kingdom.jpg'),
  ('Mombasa', 'https://nomads.com/assets/img/places/mombasa-kenya.jpg'),
  ('Lusaka', 'https://nomads.com/assets/img/places/lusaka-zambia.jpg'),
  ('Gaborone', 'https://nomads.com/assets/img/places/gaborone-botswana.jpg'),
  ('Antananarivo', 'https://nomads.com/assets/img/places/antananarivo-madagascar.jpg'),
  ('Freetown', 'https://nomads.com/assets/img/places/freetown-sierra-leone.jpg'),
  ('Conacri', 'https://nomads.com/assets/img/places/conakry-guinea.jpg'),
  ('Harare', 'https://nomads.com/assets/img/places/harare-zimbabwe.jpg'),
  ('Victoria', 'https://nomads.com/assets/img/places/victoria-seychelles.jpg'),
  ('Pretória', 'https://nomads.com/assets/img/places/pretoria-south-africa.jpg'),
  ('Rabat', 'https://nomads.com/assets/img/places/rabat-morocco.jpg'),
  ('Livingstone', 'https://nomads.com/assets/img/places/livingstone-zambia.jpg'),
  ('El Gouna', 'https://nomads.com/assets/img/places/el-gouna-egypt.jpg'),
  ('Gizé', 'https://nomads.com/assets/img/places/giza-egypt.jpg'),
  ('Luxor', 'https://nomads.com/assets/img/places/luxor-egypt.jpg'),
  ('Dammam', 'https://nomads.com/assets/img/places/dammam-saudi-arabia.jpg'),
  ('Duhok', 'https://nomads.com/assets/img/places/duhok-kurdistan.jpg'),
  ('Kirkuk', 'https://nomads.com/assets/img/places/kirkuk-kurdistan.jpg'),
  ('Dahab', 'https://nomads.com/assets/img/places/dahab-egypt.jpg'),
  ('Kuwait City', 'https://nomads.com/assets/img/places/kuwait-city-kuwait.jpg'),
  ('Manama', 'https://nomads.com/assets/img/places/manama-bahrain.jpg'),
  ('Jerusalém', 'https://nomads.com/assets/img/places/jerusalem-israel.jpg'),
  ('Haifa', 'https://nomads.com/assets/img/places/haifa-israel.jpg'),
  ('Erbil', 'https://nomads.com/assets/img/places/erbil-kurdistan.jpg'),
  ('Uluwatu', 'https://nomads.com/assets/img/places/uluwatu-bali-indonesia.jpg'),
  ('Naha (Okinawa)', 'https://nomads.com/assets/img/places/naha-okinawa-japan.jpg'),
  ('Guangzhou', 'https://nomads.com/assets/img/places/guangzhou-china.jpg'),
  ('Weligama', 'https://nomads.com/assets/img/places/weligama-sri-lanka.jpg'),
  ('Hangzhou', 'https://nomads.com/assets/img/places/hangzhou-china.jpg'),
  ('Daejeon', 'https://nomads.com/assets/img/places/daejeon-south-korea.jpg'),
  ('Nakhon Ratchasima', 'https://nomads.com/assets/img/places/nakhon-ratchasima-thailand.jpg'),
  ('Chengdu', 'https://nomads.com/assets/img/places/chengdu-china.jpg'),
  ('Denpasar', 'https://nomads.com/assets/img/places/denpasar-bali-indonesia.jpg'),
  ('Calcutá', 'https://nomads.com/assets/img/places/kolkata-india.jpg'),
  ('Ko Lanta', 'https://nomads.com/assets/img/places/ko-lanta-thailand.jpg'),
  ('Cemagi (Bali)', 'https://nomads.com/assets/img/places/canggu-bali-indonesia.jpg'),
  ('Xangai', 'https://nomads.com/assets/img/places/shanghai-china.jpg'),
  ('Makassar', 'https://nomads.com/assets/img/places/makassar-indonesia.jpg'),
  ('Krabi', 'https://nomads.com/assets/img/places/krabi-thailand.jpg'),
  ('Astana', 'https://nomads.com/assets/img/places/astana-kazakhstan.jpg'),
  ('La Union', 'https://nomads.com/assets/img/places/la-union-philippines.jpg'),
  ('Hiroshima', 'https://nomads.com/assets/img/places/hiroshima-japan.jpg'),
  ('Thimphu', 'https://nomads.com/assets/img/places/thimphu-bhutan.jpg'),
  ('Tainan', 'https://nomads.com/assets/img/places/tainan-taiwan.jpg'),
  ('Pequim', 'https://nomads.com/assets/img/places/beijing-china.jpg'),
  ('Gili Air', 'https://nomads.com/assets/img/places/gili-air-indonesia.jpg'),
  ('Jodhpur', 'https://nomads.com/assets/img/places/jodhpur-india.jpg'),
  ('Senggigi (Lombok)', 'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=600&q=80'),
  ('Matara', 'https://nomads.com/assets/img/places/matara-sri-lanka.jpg'),
  ('Lahore', 'https://nomads.com/assets/img/places/lahore-pakistan.jpg'),
  ('Vadodara', 'https://nomads.com/assets/img/places/vadodara-india.jpg'),
  ('Christchurch', 'https://nomads.com/assets/img/places/christchurch-new-zealand.jpg'),
  ('Hagatña', 'https://nomads.com/assets/img/places/hagatna-guam.jpg'),
  ('Wanaka', 'https://nomads.com/assets/img/places/wanaka-new-zealand.jpg'),
  ('Funafuti', 'https://nomads.com/assets/img/places/funafuti-tuvalu.jpg'),
  ('Port Moresby', 'https://nomads.com/assets/img/places/port-moresby-papua-new-guinea.jpg'),
  ('Hobart', 'https://nomads.com/assets/img/places/hobart-australia.jpg'),
  ('Wollongong', 'https://nomads.com/assets/img/places/wollongong-australia.jpg'),
  ('Nukualofa', 'https://nomads.com/assets/img/places/nukualofa-tonga.jpg'),
  ('Honiara', 'https://nomads.com/assets/img/places/honiara-solomon-islands.jpg'),
  ('Dunedin', 'https://nomads.com/assets/img/places/dunedin-new-zealand.jpg'),
  ('Byron Bay', 'https://nomads.com/assets/img/places/byron-bay-australia.jpg'),
  ('Kauai', 'https://nomads.com/assets/img/places/kauai-hawaii-united-states.jpg'),
  ('Canberra', 'https://nomads.com/assets/img/places/canberra-australia.jpg'),
  ('Hilo', 'https://nomads.com/assets/img/places/hilo-hawaii-united-states.jpg'),
  ('Port Vila', 'https://nomads.com/assets/img/places/port-vila-vanuatu.jpg'),
  ('Darwin', 'https://nomads.com/assets/img/places/darwin-australia.jpg'),
  ('Dededo', 'https://nomads.com/assets/img/places/dededo-guam.jpg'),
  ('Avarua', 'https://nomads.com/assets/img/places/avarua-cook-islands.jpg'),
  ('Nova Iorque', 'https://nomads.com/assets/img/places/new-york-city-ny-united-states.jpg'),
  ('São Francisco', 'https://nomads.com/assets/img/places/san-francisco-ca-united-states.jpg'),
  ('Las Vegas', 'https://nomads.com/assets/img/places/las-vegas-nv-united-states.jpg'),
  ('Orlando', 'https://nomads.com/assets/img/places/orlando-fl-united-states.jpg'),
  ('Boston', 'https://nomads.com/assets/img/places/boston-ma-united-states.jpg'),
  ('Joanesburgo', 'https://nomads.com/assets/img/places/johannesburg-south-africa.jpg'),
  ('Maui', 'https://images.unsplash.com/photo-1507876466758-bc54f384809c?w=600&q=80'),
  ('Houston', 'https://nomads.com/assets/img/places/houston-tx-united-states.jpg'),
  ('Rangum', 'https://nomads.com/assets/img/places/yangon-myanmar.jpg'),
  ('Argel', 'https://nomads.com/assets/img/places/algiers-algeria.jpg'),
  ('Oakland', 'https://nomads.com/assets/img/places/oakland-ca-united-states.jpg'),
  ('Calgary', 'https://nomads.com/assets/img/places/calgary-canada.jpg'),
  ('Maceió', 'https://images.unsplash.com/photo-1601329275729-631bf7b4e149?w=800&q=80'),
  ('Aracaju', 'https://images.unsplash.com/photo-1662781288502-5d3a42cf4290?w=800&q=80'),
  ('Búzios', 'https://images.unsplash.com/photo-1508272961731-dc692d634a79?w=800&q=80'),
  ('Gramado', 'https://images.unsplash.com/photo-1690907938160-133874466bb0?w=800&q=80'),
  ('Paraty', 'https://images.unsplash.com/photo-1738350142684-6c1e0d81896e?w=800&q=80'),
  ('Ouro Preto', 'https://images.unsplash.com/photo-1659621065449-009507f1b7c1?w=800&q=80'),
  ('Fernando de Noronha', 'https://images.unsplash.com/photo-1642889014528-8e41d350ac35?w=800&q=80'),
  ('Jericoacoara', 'https://images.unsplash.com/photo-1524943999231-42946c42ee78?w=800&q=80'),
  ('Balneário Camboriú', 'https://images.unsplash.com/photo-1541107617727-94bbb769fdef?w=800&q=80'),
  ('Bonito', 'https://images.unsplash.com/photo-1669639613055-7c5a1b28eddd?w=800&q=80'),
  ('Chapada Diamantina', 'https://images.unsplash.com/photo-1698315495764-3e32b61ea1c0?w=800&q=80'),
  ('Ilhabela', 'https://images.unsplash.com/photo-1668295502115-a80fc3ef1377?w=800&q=80'),
  ('Porto Seguro', 'https://images.unsplash.com/photo-1615129614910-042efe893485?w=800&q=80'),
  ('Porto de Galinhas', 'https://images.unsplash.com/photo-1698760043845-02becc795cdd?w=800&q=80'),
  ('Arraial do Cabo', 'https://images.unsplash.com/photo-1633130172061-e539b61df05f?w=800&q=80'),
  ('Lençóis Maranhenses', 'https://images.unsplash.com/photo-1574186150360-b77724e79e1f?w=800&q=80'),
  ('Morro de São Paulo', 'https://images.unsplash.com/photo-1594358037468-121d0af96ca2?w=800&q=80'),
  ('Olinda', 'https://images.unsplash.com/photo-1617172966463-3c52a9d0c18f?w=800&q=80'),
  ('Ubatuba', 'https://images.unsplash.com/photo-1661692755472-d5f29e2edb7a?w=800&q=80'),
  ('Ilhéus', 'https://images.unsplash.com/photo-1603719846095-12a6cdffdcd7?w=800&q=80'),
  ('Santos', 'https://images.unsplash.com/photo-1531517760206-6ccdac026a62?w=800&q=80'),
  ('Petrópolis', 'https://images.unsplash.com/photo-1730132432963-e88edf654eec?w=800&q=80'),
  ('Tiradentes', 'https://images.unsplash.com/photo-1708457471461-ab3509ab9ab3?w=800&q=80'),
  ('Canela', 'https://images.unsplash.com/photo-1612209410552-24756489cf07?w=800&q=80'),
  ('Ribeirão Preto', 'https://images.unsplash.com/photo-1523962389844-25940ebd2226?w=800&q=80'),
  ('Londrina', 'https://images.unsplash.com/photo-1687821016316-573453ff4ebe?w=800&q=80'),
  ('Maringá', 'https://images.unsplash.com/photo-1753973690189-bdf847114773?w=800&q=80'),
  ('Cuiabá', 'https://images.unsplash.com/photo-1495480857653-79a3f39d99af?w=800&q=80'),
  ('Palmas', 'https://images.unsplash.com/photo-1662998305968-2d52d2ccd7ba?w=800&q=80'),
  ('Teresina', 'https://images.unsplash.com/photo-1667819955012-9aff07d8fce5?w=800&q=80'),
  ('Niterói', 'https://images.unsplash.com/photo-1672778491063-f6a5b461595f?w=800&q=80'),
  ('Pirenópolis', 'https://images.unsplash.com/photo-1611937315268-0899710284c9?w=800&q=80'),
  ('Alto Paraíso de Goiás', 'https://images.unsplash.com/photo-1611945959114-47dfbd5cb005?w=800&q=80'),
  ('Caraíva', 'https://images.unsplash.com/photo-1749648495131-772de4f86426?w=800&q=80'),
  ('Praia do Forte', 'https://images.unsplash.com/photo-1745681278433-4f45b29fb3c4?w=800&q=80')
ON CONFLICT (city) DO UPDATE SET
  image_url = EXCLUDED.image_url,
  updated_at = NOW();

-- 4) Trigger para auto-atualizar updated_at
CREATE OR REPLACE FUNCTION update_destination_images_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_destination_images_updated_at ON destination_images;
CREATE TRIGGER trg_destination_images_updated_at
  BEFORE UPDATE ON destination_images
  FOR EACH ROW
  EXECUTE FUNCTION update_destination_images_updated_at();

-- 5) Habilitar RLS
ALTER TABLE destination_images ENABLE ROW LEVEL SECURITY;

-- Politica para leitura publica
DROP POLICY IF EXISTS "Allow public read" ON destination_images;
CREATE POLICY "Allow public read" ON destination_images
  FOR SELECT USING (true);

-- Politica para escrita apenas por service_role
DROP POLICY IF EXISTS "Allow service write" ON destination_images;
CREATE POLICY "Allow service write" ON destination_images
  FOR ALL USING (auth.role() = 'service_role');
